baseURL: "https://tobyscott.dev/"
languageCode: "en-au"
title: "Toby Scott"
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
googleAnalytics: G-91GQY1XE47

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: search
      name: Search
      url: /search
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives
      weight: 30
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 40
    - identifier:
      name: GitHub
      url: https://github.com/tobyscott25
      weight: 50

params:
  # SEO
  title: Toby Scott
  description: My blog of docs, thoughts and technical discovery.
  keywords: [Blog, Portfolio, Software Engineer]
  author: Toby Scott
  DateFormat: "2 January 2006"

  assets:
    favicon: "favicon.svg"

  defaultTheme: auto
  homeInfoParams:
    Title: Welcome 👋
    Content: Software Engineer, Greater Melbourne Area | Currently working on [Safety Beacon (NFP)](https://github.com/safetybeacon) and [Study Score](https://studyscore.app)
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/tobyscott25"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/6000173"
    - name: "linkedin"
      url: "https://linkedin.com/in/toby-scott"
    - name: "mastodon"
      url: "https://mas.to/@tobyscott"
    - name: "youtube"
      url: "https://youtube.com/@TobyScott"
    - name: "email"
      url: "mailto:hi@tobyscott.dev"
  ShowShareButtons: true
  ShareButtons: ["twitter", "reddit", "linkedin"]
  # ShowReadingTime: true
  # ShowToc: true
  ShowBreadCrumbs: true
  # ShowWordCount: true
  editPost:
    URL: "https://github.com/tobyscott25/tobyscott.dev/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  ShowCodeCopyButtons: true
  # ShowPostNavLinks: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
