baseURL: "https://tobyscott.dev/"
languageCode: "en-au"
title: "Toby Scott"
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
googleAnalytics: G-91GQY1XE47

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags
      weight: 40
    - identifier: github
      name: GitHub
      url: https://github.com/tobyscott25
      weight: 50

params:
  # SEO
  title: Toby Scott
  description: Personal blog of thoughts and technical discoveries
  keywords:
    [Blog, Portfolio, Software Engineer, Tutorial, TypeScript, Go, Linux]
  author: Toby Scott

  DateFormat: "2 January 2006"
  assets:
    favicon: "favicon.svg"
  defaultTheme: auto

  homeInfoParams:
    Title: Welcome 👋
    Content: Software Engineer, Greater Melbourne Area | Currently working on [Safety Beacon (NFP)](https://github.com/safetybeacon) and [Study Score](https://studyscore.app)

  profileMode:
    enabled: false # Disable this to change to "home info" mode
    title: Toby Scott # optional, default will be site title
    subtitle: Software Engineer, Greater Melbourne Area
    imageUrl: "/avatar.png" # optional
    imageTitle: "Avatar" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size
    # buttons:
    #   - name: Blog posts
    #     url: "/posts/"
    #   - name: Projects
    #     url: "/projects/"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/tobyscott25"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/6000173"
    - name: "linkedin"
      url: "https://linkedin.com/in/toby-scott"
    - name: "mastodon"
      url: "https://mas.to/@tobyscott"
    - name: "youtube"
      url: "https://youtube.com/@TobyScott"
    - name: "email"
      url: "mailto:hi@tobyscott.dev"

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true

  ShowShareButtons: true
  ShareButtons: ["linkedin", "reddit", "twitter"]
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  # ShowWordCount: true
  editPost:
    URL: "https://github.com/tobyscott25/tobyscott.dev/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  ShowCodeCopyButtons: true
  # ShowPostNavLinks: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
