name: Test auto-toot

on:
  push:
    branches: [autotoot]
  workflow_dispatch:

jobs:
  post-to-mastodon:
    name: Post to Mastodon
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go mod download
      - name: Auto-toot
        env:
          MASTODON_ACCESS_TOKEN: ${secrets.MASTODON_ACCESS_TOKEN}
          MASTODON_ORIGIN: ${secrets.MASTODON_ORIGIN}
          BLOG_ORIGIN: ${secrets.BLOG_ORIGIN}
        working-directory: ./auto-toot
        run: go run main.go
