name: first-github-action
on:
  push:
    branches:
      - main
jobs:
  test-changes:
    name: Test Changes
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Testing changes...'
  deploy-changes:
    name: Deploy Changes
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying changes...'