name: deploy

on:
  push:
    branches:
      - main

jobs:
  # test-changes:
  #   name: Test Changes
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - run: echo 'Testing changes...'

  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Deploying changes...'

      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install Hugo within GH Action runner
        run: sudo apt install hugo -y

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Add host to known hosts within GH Action runner
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Build and upload Hugo site
        run: |
          hugo --minify
          mv public html
          sudo scp -r html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/tobyscott.dev/

      # - name: Build and upload Hugo site
      #   run: |
      #     hugo --minify
      #     mv public html
      #     rsync -avz -e ssh ./html/ ${{ secrets.SSH_HOST }}:/var/www/html/tobyscott.dev/html